import jsPDF from "jspdf";

function PDFReport({
  selectedMonth,
  income,
  expense,
  balance,
  monthlyBudget,
  transactions,
}) {
  const generatePDF = () => {
    const pdf = new jsPDF();

    const savingsPercentage =
      income > 0
        ? (balance / income) * 100
        : 0;

    const budgetUsedPercentage =
      monthlyBudget > 0
        ? (expense / monthlyBudget) * 100
        : 0;

    const formatMoney = (amount) => {
      return Number(amount).toLocaleString(
        "en-IN"
      );
    };

    /* ================================
       TITLE
       ================================ */

    pdf.setFontSize(22);
    pdf.setFont("helvetica", "bold");

    pdf.text(
      "Expense Tracker",
      20,
      25
    );

    pdf.setFontSize(15);
    pdf.setFont("helvetica", "normal");

    pdf.text(
      "Monthly Financial Report",
      20,
      35
    );

    pdf.setFontSize(11);

    pdf.text(
      `Month: ${selectedMonth}`,
      20,
      45
    );

    /* ================================
       FINANCIAL SUMMARY
       ================================ */

    pdf.setFontSize(15);
    pdf.setFont("helvetica", "bold");

    pdf.text(
      "Financial Summary",
      20,
      62
    );

    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");

    pdf.text(
      `Total Income: Rs. ${formatMoney(
        income
      )}`,
      25,
      75
    );

    pdf.text(
      `Total Expenses: Rs. ${formatMoney(
        expense
      )}`,
      25,
      85
    );

    pdf.text(
      `Net Balance: Rs. ${formatMoney(
        balance
      )}`,
      25,
      95
    );

    pdf.text(
      `Savings Percentage: ${savingsPercentage.toFixed(
        1
      )}%`,
      25,
      105
    );

    pdf.text(
      `Monthly Budget: Rs. ${formatMoney(
        monthlyBudget
      )}`,
      25,
      115
    );

    pdf.text(
      `Budget Used: ${budgetUsedPercentage.toFixed(
        1
      )}%`,
      25,
      125
    );

    /* ================================
       TRANSACTIONS
       ================================ */

    pdf.setFontSize(15);
    pdf.setFont("helvetica", "bold");

    pdf.text(
      "Transactions",
      20,
      145
    );

    pdf.setFontSize(10);
    pdf.setFont("helvetica", "bold");

    pdf.text(
      "Date",
      20,
      158
    );

    pdf.text(
      "Type",
      50,
      158
    );

    pdf.text(
      "Category",
      80,
      158
    );

    pdf.text(
      "Amount",
      125,
      158
    );

    pdf.text(
      "Description",
      160,
      158
    );

    pdf.setFont("helvetica", "normal");

    let y = 168;

    transactions.forEach(
      (transaction) => {
        if (y > 275) {
          pdf.addPage();

          y = 20;
        }

        pdf.text(
          transaction.date || "-",
          20,
          y
        );

        pdf.text(
          transaction.type || "-",
          50,
          y
        );

        pdf.text(
          transaction.category || "-",
          80,
          y
        );

        pdf.text(
          `Rs. ${formatMoney(
            transaction.amount
          )}`,
          125,
          y
        );

        const description =
          transaction.description || "-";

        pdf.text(
          description.substring(
            0,
            25
          ),
          160,
          y
        );

        y += 9;
      }
    );

    /* ================================
       FOOTER
       ================================ */

    pdf.setFontSize(9);

    pdf.text(
      "Generated by Expense Tracker",
      20,
      290
    );

    /* ================================
       DOWNLOAD
       ================================ */

    pdf.save(
      `expense-report-${selectedMonth}.pdf`
    );
  };

  return (
    <div className="pdf-report">

      <button
        className="pdf-btn"
        onClick={generatePDF}
      >
        📄 Download PDF Report
      </button>

    </div>
  );
}

export default PDFReport;